# Generated by Django 6.0.6 on 2026-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.office365.com', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_comment_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_sla_breach',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_status_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_ticket_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_ticket_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_ticket_resolved',
            field=models.BooleanField(default=True),
        ),
    ]
