# Generated by Django 6.0.6 on 2026-07-02 05:08

import branding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_systemsettings_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_headline',
            field=models.CharField(blank=True, default='Resolve faster.\nWork smarter.', help_text='Login page hero headline. Use a newline for a two-line heading.', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_highlights',
            field=models.JSONField(blank=True, default=branding.models.default_login_highlights, help_text='List of {icon, text} bullet points shown on the login page.'),
        ),
    ]
