# Generated by Django 6.0.6 on 2026-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_systemsettings_login_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='powered_by_text',
            field=models.CharField(blank=True, default='Powered by GSH & ISH OMAN IT', help_text='Shown in the sidebar footer and on the login page. Leave blank to hide.', max_length=200),
        ),
    ]
