# Generated by Django 6.0.6 on 2026-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_systemsettings_powered_by_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_idle_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes of inactivity before automatic logout. A user with a personal override (Users -> Edit User) uses that value instead.'),
        ),
    ]
