# Generated by Django 6.0.6 on 2026-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_systemsettings_default_idle_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='show_sla_due_in_emails',
            field=models.BooleanField(default=True, help_text='Show Response Due / Resolution Due / SLA Due lines in notification emails.'),
        ),
    ]
