# Generated by Django 6.0.6 on 2026-07-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0006_systemsettings_show_sla_due_in_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_sla_due_in_emails',
        ),
    ]
