# Generated by Django 6.0.6 on 2026-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0007_remove_systemsettings_show_sla_due_in_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_account_sid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_comment_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_sla_breach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_status_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_ticket_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_ticket_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_notify_on_ticket_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_provider',
            field=models.CharField(choices=[('meta_cloud', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio'), ('generic', 'Generic Webhook')], default='meta_cloud', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_sender_number',
            field=models.CharField(blank=True, help_text='Twilio WhatsApp-enabled sender, e.g. whatsapp:+14155238886', max_length=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_template_language',
            field=models.CharField(blank=True, default='en_US', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_template_name',
            field=models.CharField(blank=True, default='ticket_notification', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
