# Generated by Django 6.0.6 on 2026-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Ticket Created (to requester)'), ('ticket_dept_notification', 'New Ticket (to department)'), ('ticket_assigned', 'Ticket Assigned (to agent)'), ('status_updated', 'Status Updated (to requester)'), ('comment_added', 'New Reply (to requester)'), ('ticket_resolved', 'Ticket Resolved (to requester)'), ('ticket_escalated', 'Ticket Escalated (to manager)'), ('sla_breach', 'SLA Breach Alert')], max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, help_text='If off, the built-in default content is used.')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
