# Generated by Django 6.0.6 on 2026-07-01 17:53, hand-edited to preserve data:
# converts the hardcoded 4-choice `role` CharField into a `Role` FK, seeding
# 4 Role rows whose permissions reproduce today's exact access matrix (see
# the RBAC plan for the full mapping), then migrates every existing user's
# string role value onto the matching new Role row.

import django.db.models.deletion
from django.db import migrations, models


END_USER_PERMS = [
    'tickets.view', 'tickets.add', 'tickets.edit',
    'directory_tabs.view', 'directory_portals.view', 'portal_categories.view',
    'departments.view',
]

AGENT_PERMS = END_USER_PERMS + [
    'tickets.claim', 'tickets.internal_note', 'tickets.escalate',
]

MANAGER_PERMS = [
    'tickets.view', 'tickets.add', 'tickets.edit', 'tickets.delete',
    'tickets.claim', 'tickets.internal_note', 'tickets.manage_escalated',
    'directory_tabs.view', 'directory_tabs.add', 'directory_tabs.edit',
    'directory_portals.view', 'directory_portals.add', 'directory_portals.edit',
    'portal_categories.view',
    'departments.view',
    'reports.view', 'audit.view',
]

ROLE_SEED = {
    'end_user': {'is_super': False, 'permissions': END_USER_PERMS},
    'agent': {'is_super': False, 'permissions': AGENT_PERMS},
    'manager': {'is_super': False, 'permissions': MANAGER_PERMS},
    'admin': {'is_super': True, 'permissions': []},
}


def seed_roles_and_migrate_users(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')

    role_objs = {}
    for name, cfg in ROLE_SEED.items():
        role_objs[name] = Role.objects.create(name=name, is_super=cfg['is_super'], permissions=cfg['permissions'])

    for user in User.objects.all():
        old_value = user.role  # still the raw string at this point in the migration
        role = role_objs.get(old_value) or role_objs['end_user']
        user.role_new_id = role.id
        user.save(update_fields=['role_new'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_super', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_new',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='users', to='users.role',
            ),
        ),
        migrations.RunPython(seed_roles_and_migrate_users, noop_reverse),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_new',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
    ]
