# Generated by Django 6.0.6 on 2026-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignable_roles',
            field=models.ManyToManyField(blank=True, related_name='assignable_users', to='users.role'),
        ),
    ]
