# Generated by Django 6.0.6 on 2026-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_assignable_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idle_timeout_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides the system default idle-logout time for this user. Leave blank to use the default (Settings -> Portal).', null=True),
        ),
    ]
