# Generated by Django 6.0.6 on 2026-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_idle_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
