# Generated by Django 6.0.6 on 2026-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_note',
            field=models.TextField(blank=True, help_text='Mandatory note explaining how the ticket was resolved or why it was closed/cancelled.'),
        ),
    ]
