# Generated by Django 6.0.6 on 2026-07-01 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_portalcategory_portal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcategory',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_portal_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
