# Generated by Django 6.0.6 on 2026-07-01 16:15, hand-edited to preserve data:
# converts the hardcoded facility/contact_type split into admin-managed
# DirectoryTab rows so the Directory feature isn't tied to any one
# organization's naming (was: GSH/GSP x Telephone/Email).

import django.db.models.deletion
from django.db import migrations, models


FACILITY_LABELS = {'gsh': 'GSH', 'gsp': 'GSP'}
CONTACT_TYPE_LABELS = {'telephone': 'Telephone', 'email': 'Email'}


def populate_tabs(apps, schema_editor):
    DirectoryTab = apps.get_model('directory', 'DirectoryTab')
    StaffDirectoryEntry = apps.get_model('directory', 'StaffDirectoryEntry')

    tabs_by_key = {}
    order = 0
    for entry in StaffDirectoryEntry.objects.all():
        key = (entry.facility, entry.contact_type)
        if key not in tabs_by_key:
            name = f'{FACILITY_LABELS.get(entry.facility, entry.facility)} {CONTACT_TYPE_LABELS.get(entry.contact_type, entry.contact_type)}'.strip()
            tab, _ = DirectoryTab.objects.get_or_create(name=name, defaults={'order': order})
            tabs_by_key[key] = tab
            order += 1
        entry.tab = tabs_by_key[key]
        entry.save(update_fields=['tab'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_portalcategory_allowed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='staffdirectoryentry',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='staffdirectoryentry',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='directory.directorytab'),
        ),
        migrations.RunPython(populate_tabs, noop_reverse),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='facility',
        ),
    ]
