# Generated by Django 6.0.6 on 2026-07-01 16:30, hand-edited to preserve data:
# converts the fixed extn/room_no/location/contact/email/department_label
# columns into per-tab, admin-managed DirectoryField definitions + a JSON
# `values` blob on each entry, so the set of "details" per tab is no longer
# hardcoded.

from django.db import migrations, models
import django.db.models.deletion


LEGACY_FIELD_LABELS = [
    ('extn', 'Extension'),
    ('room_no', 'Room No'),
    ('location', 'Location'),
    ('contact', 'Mobile Contact'),
    ('email', 'Email'),
    ('department_label', 'Department'),
]


def populate_custom_fields(apps, schema_editor):
    DirectoryTab = apps.get_model('directory', 'DirectoryTab')
    DirectoryField = apps.get_model('directory', 'DirectoryField')
    StaffDirectoryEntry = apps.get_model('directory', 'StaffDirectoryEntry')

    for tab in DirectoryTab.objects.all():
        entries = list(StaffDirectoryEntry.objects.filter(tab=tab))
        order = 0
        field_by_column = {}
        for column, label in LEGACY_FIELD_LABELS:
            if any(getattr(e, column) for e in entries):
                field_by_column[column] = DirectoryField.objects.create(tab=tab, name=label, order=order)
                order += 1

        for entry in entries:
            values = {}
            for column, field in field_by_column.items():
                val = getattr(entry, column)
                if val:
                    values[str(field.id)] = val
            entry.values = values
            entry.save(update_fields=['values'])

    # Entries with no tab (shouldn't normally happen, but be safe) keep an
    # empty values dict - nothing to migrate for those.


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_convert_to_dynamic_tabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='directory.directorytab')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('tab', 'name')},
            },
        ),
        migrations.AddField(
            model_name='staffdirectoryentry',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='staffdirectoryentry',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='directory.directorytab'),
        ),
        migrations.RunPython(populate_custom_fields, noop_reverse),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='department_label',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='extn',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='room_no',
        ),
    ]
