# Generated by Django 6.0.6 on 2026-07-01 16:41, hand-edited to preserve data:
# "Name" stops being a hardcoded model column and becomes an ordinary
# DirectoryField (order -1, so it still sorts first by default) that can be
# renamed or deleted per-tab just like any other detail.

from django.db import migrations, models


def move_name_into_fields(apps, schema_editor):
    DirectoryField = apps.get_model('directory', 'DirectoryField')
    StaffDirectoryEntry = apps.get_model('directory', 'StaffDirectoryEntry')

    name_field_by_tab = {}
    for entry in StaffDirectoryEntry.objects.all():
        if not entry.name or entry.tab_id is None:
            continue
        if entry.tab_id not in name_field_by_tab:
            existing = DirectoryField.objects.filter(name='Name', tab_id=entry.tab_id).first()
            if existing:
                field = existing
            else:
                # Push existing fields out of the way so "Name" sorts first.
                DirectoryField.objects.filter(tab_id=entry.tab_id).update(order=models.F('order') + 1)
                field = DirectoryField.objects.create(tab_id=entry.tab_id, name='Name', order=0)
            name_field_by_tab[entry.tab_id] = field
        field = name_field_by_tab[entry.tab_id]
        entry.values[str(field.id)] = entry.name
        entry.save(update_fields=['values'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_custom_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdirectoryentry',
            options={'ordering': ['id']},
        ),
        migrations.RunPython(move_name_into_fields, noop_reverse),
        migrations.RemoveField(
            model_name='staffdirectoryentry',
            name='name',
        ),
    ]
