# Generated by Django 6.0.6 on 2026-07-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_entry_name_becomes_field'),
        ('users', '0003_dynamic_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalcategory',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='portalcategory',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='allowed_portal_categories', to='users.role'),
        ),
    ]
