# Generated by Django 6.0.6 on 2026-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_reassigned', 'Ticket Reassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_reopened', 'Ticket Reopened'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('login', 'User Login'), ('logout', 'User Logout'), ('vault_revealed', 'Vault Password Revealed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed')], max_length=50),
        ),
    ]
