# Generated by Django 6.0.6 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Raw User-Agent header, for device/browser display.', max_length=300),
        ),
    ]
